language: ruby
rvm:
  - '2.4.10'
  - '2.5.8'
  - '2.6.6'
  - '2.7.2'
env:
  global:
    - CC_TEST_REPORTER_ID=b82d06c331e2b020fe95a3f884bfb04134156d8c2f740d570eeb550130506e22
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
